elastic-job:
  zookeeper-url: localhost:2181
  namespace: elastic-job-demo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elastic-job-demo?useSSL=false&useUnicode=true&AllowPublicKeyRetrieval=True&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  # mapper.xml
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: cn.layfolk.elasticjob.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
